env:
  es2021: true
  node: true
extends:
  - standard
  - prettier
plugins:
  - unused-imports
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
globals:
  test: true
  expect: true
  describe: true
rules:
  "unused-imports/no-unused-imports": error
  "unused-imports/no-unused-vars": error
  "import/order":
    - error
    - groups:
        - builtin
        - external
        - internal
      alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
      pathGroups:
        - pattern: src/**
          group: internal
